# Generated by Django 3.2.20 on 2023-08-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0006_auto_20230811_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
