# Generated by Django 3.2.20 on 2023-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0007_alter_workoutprogram_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutprogram',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
