# Generated by Django 3.2.20 on 2023-08-11 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0008_alter_workoutprogram_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
