# Generated by Django 3.2.20 on 2023-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0009_auto_20230811_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
