# Generated by Django 3.2.20 on 2023-08-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0013_auto_20230823_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('target', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='target',
        ),
        migrations.AddField(
            model_name='exerciseinprogram',
            name='exercise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='workout_programs.exercise'),
            preserve_default=False,
        ),
    ]
