# Generated by Django 3.2.20 on 2023-08-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0014_auto_20230823_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseinprogram',
            old_name='program_id',
            new_name='program',
        ),
    ]
