# Generated by Django 3.2.20 on 2023-08-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0015_rename_program_id_exerciseinprogram_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseinprogram',
            old_name='program',
            new_name='program_id',
        ),
    ]
