# Generated by Django 3.2.20 on 2023-09-06 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0017_rename_program_id_exerciseinprogram_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='sets',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('exercise_in_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='workout_programs.exerciseinprogram')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseinprogram',
            name='sets',
            field=models.ManyToManyField(to='workout_programs.Set'),
        ),
    ]
