# Generated by Django 3.2.20 on 2023-09-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0021_auto_20230920_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinprogram',
            name='sets',
        ),
    ]
