# Generated by Django 3.2.20 on 2023-09-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0026_auto_20230925_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinprogram',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='workout_programs.set'),
        ),
    ]
