# Generated by Django 3.2.20 on 2023-09-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_programs', '0029_alter_exerciseinprogram_sets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='SetInExercise',
        ),
    ]
